//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _object {
            get {
                object obj = ResourceManager.GetObject("_object", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _string {
            get {
                object obj = ResourceManager.GetObject("_string", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] array {
            get {
                object obj = ResourceManager.GetObject("array", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] functions {
            get {
                object obj = ResourceManager.GetObject("functions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t#nil#SCALAR
        ///t#nil#BOOL
        ///t#nil#ARRAY
        ///t#nil#STRING
        ///t#nil#NOTHING
        ///t#nil#ANY
        ///t#nil#NAMESPACE
        ///t#nil#NaN
        ///t#nil#IF
        ///t#nil#WHILE
        ///t#nil#FOR
        ///t#nil#SWITCH
        ///t#nil#EXCEPTION
        ///t#nil#WITH
        ///t#nil#CODE
        ///t#nil#OBJECT
        ///t#nil#VECTOR
        ///t#nil#TRANS
        ///t#nil#ORIENT
        ///t#nil#SIDE
        ///t#nil#GROUP
        ///t#nil#TEXT
        ///t#nil#SCRIPT
        ///t#nil#TARGET
        ///t#nil#JCLASS
        ///t#nil#CONFIG
        ///t#nil#DISPLAY
        ///t#nil#CONTROL
        ///t#nil#NetObject
        ///t#nil#SUBGROUP
        ///t#nil#TEAM_MEMBER
        ///t#nil#TASK
        ///t#nil#DIARY_RECORD
        ///t#nil#LOCATION
        ///b#nil#ARRAY waypointattachobject SCALA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQF_SupportInfo {
            get {
                return ResourceManager.GetString("SQF_SupportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vec3 {
            get {
                object obj = ResourceManager.GetObject("vec3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
